#!/usr/bin/env python3
"""Generate bundled Forever spell names and rank families; never runs inside the addon."""

import argparse
import datetime
import hashlib
import json
from pathlib import Path
import re
import urllib.request


SOURCE_URL = "https://talentsforever.com/data.json"
OUTPUT = Path(__file__).resolve().parents[1] / "libs/SpellRankData/Forever.lua"


def collect_families(data):
    if data["license"] != "CC-BY-4.0":
        raise ValueError("Source license changed; review it before updating")
    datetime.date.fromisoformat(data["generated"])
    families, owners = {}, {}
    for key, record in data["spell_desc"].items():
        parts = key.split("|")
        if len(parts) != 3 or not parts[0] or not parts[1] or any(ord(char) < 32 for char in key):
            raise ValueError(f"Unexpected spell key: {key!r}")
        spell_class, name, variant = parts
        rank = re.fullmatch(r"Rank ([1-9][0-9]*)", variant)
        if record["s"] != "beta" or not rank:
            continue

        spell_id = record["id"]
        if type(spell_id) is not int or not 0 < spell_id < 2147483647:
            raise ValueError(f"Invalid spell ID: {key}")
        if spell_id in owners:
            raise ValueError(f"ID {spell_id} belongs to both {owners[spell_id]} and {key}")
        owners[spell_id] = key
        family = families.setdefault((spell_class, name), {})
        number = int(rank[1])
        if number in family:
            raise ValueError(f"Duplicate rank: {key}")
        family[number] = spell_id

    result = []
    for key, ranks in sorted(families.items()):
        if sorted(ranks) != list(range(1, len(ranks) + 1)):
            raise ValueError(f"Missing ranks in {key}; review source coverage")
        if len(ranks) > 1:
            result.append((key, [ranks[rank] for rank in sorted(ranks)]))
    if not result:
        raise ValueError("Source contains no beta rank families")
    return result


def render(raw):
    data = json.loads(raw)
    families = collect_families(data)
    lines = [
        "-- Generated by scripts/update-spell-ranks.py. Do not edit by hand.",
        f"-- Source: {SOURCE_URL} (generated {data['generated']}).",
        f"-- Source SHA-256: {hashlib.sha256(raw).hexdigest()}",
        "-- CC BY 4.0; attribution and modifications: see LICENSE.txt beside this file.",
        "-- Beta spellbook ranks only; this is not a complete applied-aura catalog.",
        "local _, NS = ...",
        "",
        "local select = select",
        "local GetBuildInfo = GetBuildInfo",
        "",
        "local interfaceVersion = select(4, GetBuildInfo())",
        "if interfaceVersion < 16000 or interfaceVersion >= 20000 then",
        "  return",
        "end",
        "",
        "NS.SpellRankFamilies = {",
    ]
    for (spell_class, name), ids in families:
        quoted_name = json.dumps(name, ensure_ascii=False)
        lines.append("  { " + ", ".join(map(str, ids)) + f", name = {quoted_name} }}, -- {spell_class}")
    lines.extend(["}", ""])
    return "\n".join(lines), len(families), sum(len(ids) for _, ids in families)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, help="Read a saved data.json instead of downloading")
    parser.add_argument("--check", action="store_true", help="Validate and compare without changing the bundled file")
    args = parser.parse_args()
    if args.source:
        raw = args.source.read_bytes()
    else:
        with urllib.request.urlopen(SOURCE_URL, timeout=30) as response:
            raw = response.read()

    # Finish validation before touching the existing runtime data.
    output, families, ids = render(raw)
    if args.check:
        if OUTPUT.read_text() != output:
            parser.exit(1, "Bundled rank data differs; rerun without --check to update.\n")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output)
    print(f"Validated {families} rank families / {ids} IDs. {'Unchanged' if args.check else 'Updated'}: {OUTPUT.name}")


if __name__ == "__main__":
    main()
